// <auto-generated />
using DogHouseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogHouseService.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DogHouseService.Data.Entity.Dog", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("tail_length")
                        .HasColumnType("float");

                    b.Property<float>("weight")
                        .HasColumnType("float");

                    b.HasKey("name");

                    b.ToTable("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
